version: '2'

plugins:
  tslint:
    enabled: true
    config: tslint.json
  duplication:
    enabled: true
    config:
      languages:
        - javascript:

exclude_patterns:
  - '.api/'
  - '**/node_modules/'
  - '**/test/'
  - '**/*.d.ts'
