service: ${file(./package.json):name}

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}
  stage: ${env:ENVIRONMENT}
  timeout: 180 # 3 minutes
  memorySize: 128 # MB
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'secretsmanager:GetSecretValue'
      Resource: 'arn:aws:secretsmanager:${self:provider.region}:${aws:accountId}:*'
  environment:
    BAMBOOHR_SUBDOMAIN: ${env:BAMBOOHR_SUBDOMAIN}
    EMPLOYEE_COUNTRY_FILTER: ${env:EMPLOYEE_COUNTRY_FILTER}
    CELEBRATIONS_WEBHOOK_URL: ${env:CELEBRATIONS_WEBHOOK_URL}
    BANK_HOLIDAYS_WEBHOOK_URL: ${env:BANK_HOLIDAYS_WEBHOOK_URL}
    OFFICE_WEBHOOK_URL: ${env:OFFICE_WEBHOOK_URL}
    TIME_OFF_OFFICE_CODE: ${env:TIME_OFF_OFFICE_CODE}

plugins:
  - serverless-esbuild

functions:
  main:
    handler: src/handler.main
    events:
      - schedule: cron(0 7 ? * MON-FRI *)
