version: '3.8'

services:
  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME-localstack_main}'
    image: localstack/localstack:1.3.1
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    environment:
      - EAGER_SERVICE_LOADING=1
      - EDGE_PORT=4566
      - SERVICES=secretsmanager
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - BAMBOOHR_KEY=${BAMBOOHR_KEY:?err}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET:?err}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:?err}
    volumes:
      - ./config:/etc/localstack/init/ready.d
      - '/var/run/docker.sock:/var/run/docker.sock'
