name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BAMBOOHR_SUBDOMAIN: ${{ vars.BAMBOOHR_SUBDOMAIN }}
      BAMBOOHR_TIME_OFF_OFFICE_CODE: ${{ vars.BAMBOOHR_TIME_OFF_OFFICE_CODE }}
      EMPLOYEE_COUNTRY_FILTER: ${{ vars.EMPLOYEE_COUNTRY_FILTER }}
      SLACK_CELEBRATIONS_CHANNEL_IDS: ${{ vars.SLACK_CELEBRATIONS_CHANNEL_IDS }}
      SLACK_BANK_HOLIDAYS_CHANNEL_IDS: ${{ vars.SLACK_BANK_HOLIDAYS_CHANNEL_IDS }}
      SLACK_OFFICE_CHANNEL_IDS: ${{ vars.SLACK_OFFICE_CHANNEL_IDS }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af #v4.1.0
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Deploy
        uses: serverless/github-action@189dd6854a3b12ecff4a02c49351779f919933ca #v3.2.0
        with:
          args: deploy

