name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BAMBOOHR_SUBDOMAIN: ${{ vars.BAMBOOHR_SUBDOMAIN }}
      BAMBOOHR_TIME_OFF_OFFICE_CODE: ${{ vars.BAMBOOHR_TIME_OFF_OFFICE_CODE }}
      EMPLOYEE_COUNTRY_FILTER: ${{ vars.EMPLOYEE_COUNTRY_FILTER }}
      SLACK_CELEBRATIONS_CHANNEL_IDS: ${{ vars.SLACK_CELEBRATIONS_CHANNEL_IDS }}
      SLACK_BANK_HOLIDAYS_CHANNEL_IDS: ${{ vars.SLACK_BANK_HOLIDAYS_CHANNEL_IDS }}
      SLACK_OFFICE_CHANNEL_IDS: ${{ vars.SLACK_OFFICE_CHANNEL_IDS }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy

